### ISSUE TITLE
2nd assignment (deadline 2023-11-21)

### ISSUE THREAD

**Issue by piatrashkakanstantinas** [Aldas1/psi_webapp#50]
Official goal: continue developing an app while working in groups while using material covered in 7-10 lectures.

Unofficial goal: start using database and dependency injection. Deepen the functionality of application while being creative.

Requirements:

- [x] Relational database is used for storing data; (#30)
- [x] Create generic method, event or delegate; define at least 2 generic constraints; ?????? (Events + extensions + cache repo + dto converter service) !!Primarily extensions and cache (for generic method)
- [x] #52 (Events/ + cache repo)
- [x] Create at least 1 exception type and throw it; meaningfully deal with it; (most of the exceptions are logged to a file or a server); ??? Perhaps done ??? (#72)
- [x] #96 (extensions, tests)
- [x] Usage of threading via Thread class; (#94 )
- [x] Usage of async/await; (#92 )
- [x] Use at least 1 concurrent collection or Monitor; (#94) (thread worker)
- [x] Regex usage; (UserRequestDto)
- [x] No instances are created using 'new' keyword, dependency injection is used everywhere;
- [x] Unit and integration tests coverage at least 20%;
